#Spring Application Properties
Spring:
  application:
    name: "@project.name"
    version: "@project.version"


api:
  title: ${spring.application.name}
  version: "@api.version@"
  baseurl: "/api/${api.version}"
  description: "@project.description@"
  contact:
    name: "PRANOB JYOTI KALITA"
    email: "pranob.2008@gmail.com"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_mgmt_app_db
    password: Ch@mpion@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080