#Spring Application Properties
Spring:
  application:
    name: "@project.name"
    version: "@project.version"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_mgmt_app_db
    password: Ch@mpion@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080